### PR TITLE
Add type definitions

### PR DESCRIPTION
**Pull request by Odonno**
It's a first type definition. Not complete yet.

### CODE REVIEW

**Comment by jfbloom22** [comment]
@Odonno thx for getting this started.  I made a little more progress on the types.

```
declare module 'react-adal' {
    export interface AdalConfig {
        tenant: string,
        clientId: string,
        endpoints: {
          api: string
        },
        postLogoutRedirectUri?: string | undefined,
        redirectUri?: string | undefined,
        cacheLocation?: string | undefined,
        expireOffsetSeconds?: number | undefined
    }
    export interface CompleteAdalConfig extends AdalConfig {
        loginResource: string | undefined
    }
    export interface IAdalUser {
        userName: string,
        profile: {
            family_name: string,
            given_name: string,
            name: string,
            unique_name: string,
            ver: string
        }
    }
    export class AuthenticationContext {
        config: CompleteAdalConfig;
        constructor(adalConfig: AdalConfig);
        getCachedToken(resource: string): string | undefined;
        getCachedUser(): IAdalUser | undefined;
    }
    export function adalFetch (
        authContext: AuthenticationContext,
        resourceGuiId: string,
        fetch: any,
        url: string,
        options: any
    ): any

    export function withAdalLogin (
        authContext: AuthenticationContext,
        resourceId: string
    ): any

    export function runWithAdal(authContext: AuthenticationContext, callback: () => void, shouldLogin?: boolean): any; 
}
```

**Comment by Odonno** [comment]
@jfbloom22 Ey, That's really nice. Do you want me to take your changes or do you want to commit them in my branch?

**Comment by jfbloom22** [comment]
I realized that a lot of the missing types are related to the Azure AD JS library:  https://github.com/AzureAD/azure-activedirectory-library-for-js. Which has been typed here:  https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/adal-angular

Feel free to include my changes.  If I have time I will create a pull request with a more complete solution.

**Comment by jfbloom22** [comment]
I added a pull request here:  https://github.com/salvoravida/react-adal/pull/30

**Comment by panuhorsmalahti** [comment]
Why not make a PR to https://github.com/DefinitelyTyped/DefinitelyTyped if this won't get merged? That way it would be easy to install the types with `@types/react-adal`.

**Comment by dkorolov1** [comment]
@Odonno , @jfbloom22 , @panuhorsmalahti Hi guys, I've already added definitions to DefinitelyTyped. You can try to use them: https://www.npmjs.com/package/@types/react-adal

**Comment by salvoravida** [comment]
@dkorolev1 thank you!  would you like to make a PR for it?

**Comment by dkorolov1** [comment]
@salvoravida  Do you mean your repository? I think this is not necessary

**Comment by salvoravida** [comment]
close. thanks to @dkorolev1 for types.

**Pull request closed without merging**
